server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL} # Kubernetes Secret에서 가져온 환경 변수 사용
    username: ${DB_USERNAME} # Kubernetes Secret에서 가져온 환경 변수 사용
    password: ${DB_PASSWORD} # Kubernetes Secret에서 가져온 환경 변수 사용
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false # osiv
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none
        generate-ddl: false

#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://[endpoint]:3306/[schema_name]
#    username: [username]
#    password: [password]
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false # osiv
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        ddl-auto: none
#        generate-ddl: false